In [0]:
import numpy as np

In [0]:
#A=np.matrix(('2 -1 0;-1 2 -1;0 -1 2'))
#A=np.matrix(('1 2 3;5 6 7;7 8 9'))
#A=np.matrix(('9 -1 2;-1 8 -5;2 -5 7'))
#A=np.matrix(('4 2 0 0;2 5 2 0;0 2 5 2;0 0 2 5'))
A=np.matrix(('1 -1 -1 -1;-1 2 2 2;-1 2 3 1;-1 2 1 4'))
print(A)

[[ 1 -1 -1 -1]
 [-1  2  2  2]
 [-1  2  3  1]
 [-1  2  1  4]]


In [0]:
# check if A is positive definite
from numpy import linalg as lina
w, v = lina.eig(A)
w

array([6.89083658, 2.5029701 , 0.48718458, 0.11900874])

In [0]:
#b=np.matrix('1;-7;5')
#b=np.matrix('10;2;4')
#b=np.matrix('6;9;9;7')
b=np.matrix('-2;5;5;6')
print(b)

[[-2]
 [ 5]
 [ 5]
 [ 6]]


In [0]:
x=np.matrix('0;0;0;0')
print(x)

[[0]
 [0]
 [0]
 [0]]


In [0]:
def conjugateGradient(A, b, x):

    r = b - np.matmul(A, x)                   #residual
    p = r
    r_square_prev = np.dot(np.transpose(r), r)
    
    for i in range(len(b)):
        Ap = np.matmul(A, p)
        #alpha = r_square_prev / np.dot(p, Ap)
        alpha = r_square_prev / np.dot(np.transpose(p), Ap)
        #x = x + np.dot(np.multiply(alpha,np.eye(3)), p)
        x = x + np.multiply(alpha, p)
        r = r - np.multiply(alpha, Ap)
        #r = r - np.dot(np.multiply(alpha,np.eye(3)), Ap)
        r_square_new = np.dot(np.transpose(r), r)
        #print(np.sqrt(r_square_new))
        if np.sqrt(r_square_new) < 1e-8:  #check
            break
        beta=(r_square_new/r_square_prev)
        p = r + np.multiply(beta,p)
        r_square_prev = r_square_new
        #x_sol=x
        #print(x_sol)
        print('iteration')
        print(i)
    return x

In [0]:
x_sol=conjugateGradient(A, b, x)

iteration
0
iteration
1
iteration
2


In [0]:
x_sol

matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [0]:
import numpy as np

In [0]:
### testing multiplication result given by cublas
a=np.matrix('11 17 23 29 35;12 18 24 30 36;13 19 25 31 37;14 20 26 32 38;15 21 27 33 39;16 22 28 34 40')
b=np.matrix('11 16 21 26;12 17 22 27;13 18 23 28;14 19 24 29;15 20 25 30')
c=np.matmul(a, b)
print(c)


[[1555 2130 2705 3280]
 [1620 2220 2820 3420]
 [1685 2310 2935 3560]
 [1750 2400 3050 3700]
 [1815 2490 3165 3840]
 [1880 2580 3280 3980]]


In [0]:
1555   2130   2705   3280
   1620   2220   2820   3420
   1685   2310   2935   3560
   1750   2400   3050   3700
   1815   2490   3165   3840
   1880   2580   3280   3980

In [0]:
import numpy as np

In [0]:
A=np.matrix(('4 2 0 0;2 5 2 0;0 2 5 2;0 0 2 5'))
b=np.matrix('6;9;9;7')
x=np.matrix('0;0;0;0')

In [0]:
x_sol=conjugateGradient(A, b, x)
x_sol

In conjugateGradient method
r=
[[-2]
 [ 5]
 [ 5]
 [ 6]]
***************
r_square_prev
[[90]]
***************
----------------------------------
iteration:
0
Ap=
[[-18]
 [ 34]
 [ 33]
 [ 41]]
alpha=
[[0.1458671]]
x=
[[-0.2917342 ]
 [ 0.72933549]
 [ 0.72933549]
 [ 0.87520259]]
r=
[[0.62560778]
 [0.04051864]
 [0.18638574]
 [0.01944895]]
r_square_new=
[[0.42814476]]
beta=
[[0.00475716]]
p=
[[0.61609345]
 [0.06430446]
 [0.21017156]
 [0.04799193]]
r_square_prev
[[0.42814476]]
----------------------------------
iteration:
1
Ap=
[[ 0.29362551]
 [ 0.02884244]
 [ 0.19102207]
 [-0.08534526]]
alpha=
[[1.95672358]]
x=
[[0.91379039]
 [0.85516154]
 [1.14058314]
 [0.96910954]]
r=
[[ 0.05106383]
 [-0.01591805]
 [-0.18739165]
 [ 0.18644602]]
r_square_new=
[[0.07273865]]
beta=
[[0.16989265]]
p=
[[ 0.15573358]
 [-0.00499319]
 [-0.15168504]
 [ 0.1945995 ]]
r_square_prev
[[0.07273865]]
----------------------------------
iteration:
2
Ap=
[[ 0.11781232]
 [-0.07989106]
 [-0.4261756 ]
 [ 0.46099298]]
alpha=
[[0.

matrix([[1.],
        [1.],
        [1.],
        [1.]])